name: docker-buildx

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Extract image name
        id: image
        env:
          REPO: ${{ github.repository }}
        run: echo "name=${REPO/docker-}" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image.outputs.name }} 
          tags: |
            type=raw,latest
            type=sha,prefix=

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
