name: buildx

on:
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u matthewhuie --password-stdin
      - name: Docker Buildx
        run: |
          docker buildx build --push \
            --tag matthewhuie/samba:latest \
            --tag matthewhuie/samba:$(git rev-parse --short HEAD) \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
